### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by wenyunie** [UBC-MDS/speed_dating_analysis#74]
Let's put our change records here first and I will compile it into a final CHANGELOG.md to avoid merge conflicts.

**Comment by mishelly-h** [comment]
updated license: see branch update_license

**Comment by rorywhite200** [comment]
Removed unused references from README.md

Feedback origin: https://github.com/UBC-MDS/data-analysis-review-2023/issues/20#issuecomment-1839914849

Commit link: https://github.com/UBC-MDS/speed_dating_analysis/commit/f319cab4059e934292e515ae9a66d8f09e0cbe7f

**Comment by rorywhite200** [comment]
Made README.md file more understandable by reordering sections, rewording explanations and moving non-essential material to developers notes

Feedback origin: https://github.com/UBC-MDS/data-analysis-review-2023/issues/20#issuecomment-1839718485

Commit link: 037e28f

**Comment by monazhu** [comment]
Updated report to more explicitly mention the EDA we did for the analysis
* Feedback 1: https://github.com/UBC-MDS/data-analysis-review-2023/issues/20#issuecomment-1839914849
* Feedback 2: https://github.com/UBC-MDS/data-analysis-review-2023/issues/20#issuecomment-1842028526

We have also now expanded on our motivation for conducting the test statistic and how it relates to our question of interest
* Feedback 1: https://github.com/UBC-MDS/data-analysis-review-2023/issues/20#issuecomment-1839718485
* Feedback 2: https://github.com/UBC-MDS/data-analysis-review-2023/issues/20#issuecomment-1841769787

commit: eb4fbd312dc4a6b5ec7ea79029b53c8c6016500a

Updated data cleaning function and tests to account for edge cases, and updated the changes according to

**Comment by wenyunie** [comment]
updating the docker-compose.yml for clarification of platform for running the container
feedback from: https://github.com/UBC-MDS/data-analysis-review-2023/issues/20#issuecomment-1841769787
recorded change: https://github.com/UBC-MDS/speed_dating_analysis/pull/75

providing Rosetta as the solution of M1/M2 chips in the readme file that could be the most convenient solution
feedback from: https://github.com/UBC-MDS/data-analysis-review-2023/issues/20#issuecomment-1839718485
recorded change: https://github.com/UBC-MDS/speed_dating_analysis/pull/70

changing the phrasing of running cells to knit the file, which was confusing earlier
feedback from: milestone 1 feedback
<img width="332" alt="image" src="https://github.com/UBC-MDS/speed_dating_analysis/assets/143786716/f4562520-4d3d-43ee-94ee-094b7e7d9a86">
recorded change: https://github.com/UBC-MDS/speed_dating_analysis/pull/68

changing the readme file wording, we were given feedback we were not clear with how to open the project and activate renv
feedback from: milestone 1 feedback
<img width="327" alt="image" src="https://github.com/UBC-MDS/speed_dating_analysis/assets/143786716/52d094f0-1a9d-4c30-aaaf-2d5cf22c0054">
recorded change: https://github.com/UBC-MDS/speed_dating_analysis/pull/65


changing the readme file wording, we were given feedback we were not clear with how to open the project and activate renv
feedback from: milestone 2 feedback
<img width="303" alt="image" src="https://github.com/UBC-MDS/speed_dating_analysis/assets/143786716/87dddb92-56c3-4d45-8482-8409babae848">
<img width="317" alt="image" src="https://github.com/UBC-MDS/speed_dating_analysis/assets/143786716/9637add1-7109-4360-acbd-de1c2756c64f">
recorded change:  https://github.com/UBC-MDS/speed_dating_analysis/pull/96
